### ISSUE TITLE
List iCloud todo fails

### ISSUE THREAD

**Issue by m-urban** [tobixen/calendar-cli#16]
I just noticed that listing my iCloud's todo list fails with the following error:

```
$ ./calendar-cli.py —config-section shopping list todo list
Traceback (most recent call last):
  File "/Users/manfred/src/calendar-cli/calendar-cli.py", line 798, in <module>
    main()
  File "/Users/manfred/src/calendar-cli/calendar-cli.py", line 795, in main
    ret = args.func(caldav_conn, args)
  File "/Users/manfred/src/calendar-cli/calendar-cli.py", line 533, in todo_list
    tasks = todo_select(caldav_conn, args)
  File "/Users/manfred/src/calendar-cli/calendar-cli.py", line 430, in todo_select
    tasks = find_calendar(caldav_conn, args).todos()
  File "/usr/local/lib/python2.7/site-packages/caldav/objects.py", line 551, in todos
    response = self._query(root, 1, 'report')
  File "/usr/local/lib/python2.7/site-packages/caldav/objects.py", line 123, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.ReportError: 500 Internal Server Error
```

Adding items to the same list works fine, though:

```
$ ./calendar-cli.py --config-section shoppinglist todo add Tomatoes
Added todo item with uid=57a031c2-865b-11e5-8b6b-14109ff07266
```

**Comment by tobixen** [comment]
Probably related to https://bitbucket.org/cyrilrbt/caldav/issues/40/icloud-not-fully-supported

**Comment by m-urban** [comment]
This is actually the same issue. I forgot that I had already opened a ticket for this on BitBucket. Sorry!

**Comment by tobixen** [comment]
Have you tried the development branch of the caldav library?  I vaguely remember fixing something like this there.

I should try to get an overview and release a new version of both the caldav-library and calendar-cli eventually.

**Comment by tobixen** [comment]
Procrastinating a bit

**Comment by tobixen** [comment]
This is an issue on the caldav library side of things, hence I'm closing it here.
