### ISSUE TITLE
IndexError: list index out of range  in File "./bin/calendar-cli.py", line 66, in find_calendar

### ISSUE THREAD

**Issue by muelli** [tobixen/calendar-cli#19]
I am trying to list calendar entries:

```
./bin/calendar-cli.py --caldav-url=http://localhost:5232 --caldav-user=d --caldav-pass=d calendar agenda
Traceback (most recent call last):
  File "./bin/calendar-cli.py", line 666, in <module>
    main()
  File "./bin/calendar-cli.py", line 663, in main
    ret = args.func(caldav_conn, args)
  File "./bin/calendar-cli.py", line 328, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "./bin/calendar-cli.py", line 66, in find_calendar
    return caldav.Principal(caldav_conn).calendars()[0]
IndexError: list index out of range

```

The server gives this:

```
PROPFIND request at / received
Request headers:
{'CONTENT_LENGTH': '189',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'chinabox',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.11',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fbd3d9ec1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fbd3b55a940>,
 'wsgi.input': <socket._fileobject object at 0x7fbd3b40ec50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /
Anonymous has read access to collection /
Anonymous has write access to collection /
Request content:
<?xml version='1.0' encoding='utf-8'?>
<ns0:propfind xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV" xmlns:ns0="DAV:"><ns0:prop><ns0:current-user-principal/></ns0:prop></ns0:propfind>
Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <response>
    <href>/</href>
    <propstat>
      <prop />
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <current-user-principal />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

Answer status: 207 Unknown
PROPFIND request at / received
Request headers:
{'CONTENT_LENGTH': '182',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'chinabox',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.11',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fbd3d9ec1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fbd3b55a940>,
 'wsgi.input': <socket._fileobject object at 0x7fbd3b40ec50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /
Anonymous has read access to collection /
Anonymous has write access to collection /
Request content:
<?xml version='1.0' encoding='utf-8'?>
<ns0:propfind xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV" xmlns:ns0="DAV:"><ns0:prop><C:calendar-home-set/></ns0:prop></ns0:propfind>
Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <response>
    <href>/</href>
    <propstat>
      <prop>
        <C:calendar-home-set>
          <href>/</href>
        </C:calendar-home-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

Answer status: 207 Unknown
PROPFIND request at / received
Request headers:
{'CONTENT_LENGTH': '179',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'chinabox',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.11',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fbd3d9ec1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fbd3b55a940>,
 'wsgi.input': <socket._fileobject object at 0x7fbd3b40ec50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /
Anonymous has read access to collection /
Anonymous has write access to collection /
Anonymous has read access to item a479f75f-ce91-41f6-9052-446c74be367d
Anonymous has write access to item a479f75f-ce91-41f6-9052-446c74be367d
Request content:
<?xml version='1.0' encoding='utf-8'?>
<ns0:propfind xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV" xmlns:ns0="DAV:"><ns0:prop><ns0:resourcetype/></ns0:prop></ns0:propfind>
Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <response>
    <href>/a479f75f-ce91-41f6-9052-446c74be367d</href>
    <propstat>
      <prop>
        <resourcetype />
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
  <response>
    <href>/</href>
    <propstat>
      <prop>
        <resourcetype>
          <principal />
          <C:calendar />
          <collection />
        </resourcetype>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

Answer status: 207 Unknown
```

It's a simple radicale server.

**Comment by tobixen** [comment]
It seems odd ... the error indicates that the caldav library found no calendars, but I can see there being one calendar returned.

Would it be possible to let me access your radicale server so I could run the caldav test suite towards it and debug the issue?

**Comment by muelli** [comment]
I guess not, because I've already killed it.
I've done smth like `pip install radicale; radicale -f -D`.

**Comment by tobixen** [comment]
Wow, that's easy.   But how do you define users on that radicale server?

**Comment by muelli** [comment]
hah. I don't.

**Comment by tobixen** [comment]
so username d and password d was actually verbatim?  Is it a default user in radicale?  Otherwise, I would guess that it's needed to create a user in radicale before it's possible to view or add calendar items.

**Comment by muelli** [comment]
maybe. I don't know. I think you *can* have users, but you don't have to. But I was able to show items with DAVDroid in an Android emulator. As I wanted to have something less complicated to show the items in the DAV collection, I looked into calendar-cli.  That, however, was crashing. I think that's bad in any case.

**Comment by tobixen** [comment]
A caldav server and client without configuring any users or passwords ... wow.  If we can package radicale and calendar-cli together, we'll have a complete command-line calendaring system :-)

I'm wondering if this requires fixing in the underlying caldav-library.

**Comment by tobixen** [comment]
I regret that I so far never got time to look more into this.

I did have some issues getting Radicale to work at all with the caldav library.  Radicale seems to lack some of the support for creating and handling calendar sets, this seems to be allowed according to the RFC, but both the caldav library and the calendar-cli tool seems to require some modification to support Radicale.

I hope to get this on track in 0.12 or 0.13.

**Comment by tobixen** [comment]
caldav library 0.7.0 was released today, tests are running fine towards radicale, test framework has been fixed to spawn up radicale.  However this does not solve the problem above, one would have to create a calendar first.

With radicale, a calendar is automatically created when trying to access one - so a valid work-around would be to specify a calendar-url in the config file or in the command line options.

I think I will close this issue and raise two more issues, we should have automatic tests based on radicale and xandikos, and calendar-cli needs commands for creating a new calendar.
