### ISSUE TITLE
cannot connect to the radicale calendar

### ISSUE THREAD

**Issue by slavkoja** [tobixen/calendar-cli#25]
Hi,

after installing i have problem to connect to the my own radicale calendar server (served via Nginx -> uWSGI -> Radicale), which i am using for some years with `vdirsyncer` and `thunderbird + lightning`:
```python
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 392, in todo_select
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 84, in find_calendar
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 307, in __init__
    cup = self.get_properties([dav.CurrentUserPrincipal()])
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 172, in get_properties
    response = self._query_properties(props, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 99, in _query_properties
    return self._query(root, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 114, in _query
    url, body, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/davclient.py", line 127, in propfind
    return self.request(url or self.url, "PROPFIND", props, {'Depth': str(depth)})
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/davclient.py", line 242, in request
    raise ex
caldav.lib.error.AuthorizationError: AuthorizationError at 'https://calend.slavino.sk/slavko/hlavny.ics/', reason 'Unauthorized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/calendar-cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('calendar-cli==0.0.0', 'calendar-cli.py')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1491, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 687, in <module>
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 684, in main
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 475, in todo_list
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 394, in todo_select
  File "/usr/lib64/python3.4/site-packages/calendar_cli-0.0.0-py3.4.egg/EGG-INFO/scripts/calendar-cli.py", line 84, in find_calendar
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 307, in __init__
    cup = self.get_properties([dav.CurrentUserPrincipal()])
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 172, in get_properties
    response = self._query_properties(props, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 99, in _query_properties
    return self._query(root, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/objects.py", line 114, in _query
    url, body, depth)
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/davclient.py", line 127, in propfind
    return self.request(url or self.url, "PROPFIND", props, {'Depth': str(depth)})
  File "/usr/lib64/python3.4/site-packages/caldav-0.4.0-py3.4.egg/caldav/davclient.py", line 242, in request
    raise ex
caldav.lib.error.AuthorizationError: AuthorizationError at 'https://calend.slavino.sk/slavko/hlavny.ics/', reason 'Unauthorized'
```
The connection is forced to https and the TLS handshake seems to be completed (i am not expert, but i see no problem in wireshark). I have **HTTP Basic auth** in nginx, which works with `vdirsyncer` (from nginx's log):
```
192.168.0.1 - name [04/Apr/2016:20:00:01 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 207 6243 "-" "vdirsyncer"
```
but doesn't work with `calendar-cli` (always two requests by one command):
```
192.168.0.1 - - [04/Apr/2016:20:32:07 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 401 0 "-" "Mozilla/5.0"
192.168.0.1 - - [04/Apr/2016:20:32:07 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 401 0 "-" "Mozilla/5.0"
```
I am not able to debug the HTTP due TLS...

The config file contains (name and password removed):
```json
{ "default": 
    { "caldav_url": "https://myserver.name/name/calendar.ics/",
        "caldav-user": "name",
        "caldav-pass": "passwd"
    }
}
```
The credentials are OK, because i copy them from vdirsyncer's config and then retype them again. My knowledge ends here :-(

**Comment by slavkoja** [comment]
BTW, I tried now connect directly with caldav:
```python
client = caldav.DAVClient("https://myserver.name/name/calendar.ics/", username="name",password="passwd")
#...
```
And it seems to work:
```
192.168.0.1 - - [04/Apr/2016:20:43:10 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 401 0 "-" "Mozilla/5.0"
192.168.0.1 - name [04/Apr/2016:20:43:10 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 207 337 "-" "Mozilla/5.0"
```

**Comment by tobixen** [comment]
Please make sure that you're using the latest development branches of both caldav and calendar-cli.

Both are overdue for a new release.  I'll be prioritizing to release the caldav library first.  You can track the progress at https://bitbucket.org/cyrilrbt/caldav/issues/50/release-v05

**Comment by slavkoja** [comment]
The `calendar-cli` i cloned today from master branch, then it must be up to date.

As i mentioned early, connect directly via `caldav` works, then IMO it cannot be issue (i have `caldav 0.4.0`) from pip.

**Comment by tobixen** [comment]
Unfortunately the master branch is currently quite much out-of-sync, quite a lot of work has been done on the v0.11.0.dev branch.  Unfortunately quite much of the work in the v0.11.0.dev-branch requires that caldav v0.5.0.dev is installed.

**Comment by tobixen** [comment]
Hm.

    client = caldav.DAVClient(...)

is not supposed to initiate any traffic to the caldav server, it just sets up the object.

There was some issues with two different authorization methods being specified in the HTTP-protocol and only one of them was supported by the caldav library.  However, I don't remember if this issue was solved in caldav v0.4.0 or if the fix has gone into the to-be-released v0.5-branch.

**Comment by slavkoja** [comment]
Of course, in my `caldav` code i have more than initializing code only - it lists available calendars too, to i can see some traffic and to i can see that it works...

I do not understand CalDAV in depth, but you can believe, that i understand the HTTP and in the webserver log (i will repeat it here):
```
192.168.0.1 - - [04/Apr/2016:20:43:10 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 401 0 "-" "Mozilla/5.0"
192.168.0.1 - name [04/Apr/2016:20:43:10 +0200] "PROPFIND /name/calendar.ics/ HTTP/1.1" 207 337 "-" "Mozilla/5.0"
```
In this i see, that there was initial packet send (first line), which initiate the Unauthorized response (401) from webserver. The second line tells, that there was another request sent (the PROPFIND one), with proper credentials (the second dash after IP is replaced by the user name) with success response code (207 - *dav related). By this i see, that `caldav 0.4` understands and supports this authentication method. These two lines from the log are followed by other lines as the calendar names are fetched (then i see that it works), but are not related to initial Unauthorized problem.

The real difference is in these two lines - when i try to connect via the `calendar-cli`, there are two lines only in webserver log and both with 401 response - then there was no credentials send to the webserver and the `caldav` module properly throws the Unauthorized exception.

IMO, the credentials are not sent... I will try to take look into code, but it seems to be quite long for me Python skills ;-)

**Comment by tobixen** [comment]
try with caldav_user and caldav_password in the config, rather than caldav-user and caldav-password

**Comment by tobixen** [comment]
sorry for not responding on irc in time :-)

**Comment by slavkoja** [comment]
Don't worry about response "in time" -- i fully understand what are the free software and the free time ;-)

The underscores helps in config, now i can connect to my server -- please update README.

For now i got in the `todo list`:
```python
IndexError: list index out of range
```
I will investigate it in more depth in next days.

**Comment by tobixen** [comment]
re todo list, that's something that probably is in an inconsistent state unless you use the dev-branch both on the caldav library and the calendar-cli utility.  I was working quite much on task lists right after the last release of the caldav library, some of it may have leaked prematurely to the master branch of calendar-cli.

I'm aiming for a release of caldav 0.5 and calendar-cli 0.11 in some weeks, ref https://bitbucket.org/cyrilrbt/caldav/issues/50/release-v05

**Comment by tobixen** [comment]
fixed the README.  Closing this issue.

**Comment by tobixen** [comment]
I tried starting the radicale server from docker and run the test suite in the caldav library against it ... and there were massive breakages.  I think it all was due to some bug in the radicale server wrg of calendar creation (and all the tests start by creating a new test calendar).

I should probably look more into it, but as for now, radicale is not properly supported.
