### ISSUE TITLE
calendar-cli.py does not like Umlauts

### ISSUE THREAD

**Issue by Pupo1** [tobixen/calendar-cli#47]
I get errors whenever my new task contains a German Umlaut:

$ calendar-cli.py todo add den Ingeniör ist nichts zu schwör
Traceback (most recent call last):
  File "/usr/bin/calendar-cli.py", line 866, in <module>
    main()
  File "/usr/bin/calendar-cli.py", line 863, in main
    ret = args.func(caldav_conn, args)
  File "/usr/bin/calendar-cli.py", line 414, in todo_add
    _calendar_addics(caldav_conn, cal.to_ical(), uid, args)
  File "/usr/bin/calendar-cli.py", line 143, in _calendar_addics
    c.add_event(ics)
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 422, in add_event
    return Event(self.client, data = ical, parent = self).save()
  File "/usr/local/lib/python2.7/dist-packages/caldav/objects.py", line 718, in save
    self._create(self._instance.serialize(), self.id, path)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/local/lib/python2.7/dist-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/local/lib/python2.7/dist-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 993, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 255, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/usr/local/lib/python2.7/dist-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/usr/local/lib/python2.7/dist-packages/vobject/base.py", line 1015, in defaultSerialize
    foldOneLine(outbuf, s.getvalue(), lineLength)
  File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

**Comment by tobixen** [comment]
WFM

    $ calendar-cli.py todo add 'kjøpe øl eller bringebærsyltetøy'
    Added todo item with uid=f895b96a-c723-11e8-8fdd-9c8e99d15218

I think that the error comes from the vobject module, which version do you have that?  Have you tried with python3?

**Comment by Pupo1** [comment]
Now the todos completely stopped working.  :-(
I can still :
$ calendar-cli.py calendar add 2018-10-10 test
but 
$ calendar-cli.py todo add testing2Traceback (most recent call last):
  File "/usr/local/bin/calendar-cli.py", line 5, in <module>
    pkg_resources.run_script('calendar-cli==0.11.0', 'calendar-cli.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.11.0-py2.7.egg/EGG-INFO/scripts/calendar-cli.py", line 870, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.11.0-py2.7.egg/EGG-INFO/scripts/calendar-cli.py", line 867, in main
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.11.0-py2.7.egg/EGG-INFO/scripts/calendar-cli.py", line 417, in todo_add
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.11.0-py2.7.egg/EGG-INFO/scripts/calendar-cli.py", line 146, in _calendar_addics
    
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.5.0-py2.7.egg/caldav/objects.py", line 435, in add_event
    return Event(self.client, data = ical, parent = self).save()
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.5.0-py2.7.egg/caldav/objects.py", line 793, in save
    self._create(self._instance.serialize(), self.id, path)
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.5.0-py2.7.egg/caldav/objects.py", line 774, in _create
    {"Content-Type": 'text/calendar; charset="utf-8"'})
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.5.0-py2.7.egg/caldav/davclient.py", line 191, in put
    return self.request(url, "PUT", body, headers)
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.5.0-py2.7.egg/caldav/davclient.py", line 242, in request
    raise ex
caldav.lib.error.AuthorizationError: AuthorizationError at 'https://neueherbold.de/nextcloud/remote.php/dav/calendars/admin/639a6ec6-0685-4cb7-8541-801c2cd02484/75b9531a-c734-11e8-90ec-0024d7179re0.ics', reason 'Forbidden'

**Comment by Pupo1** [comment]
By the way, python3 gives me a different error: $ python3 /home/pupo/calendar-cli/calendar-cli.py todo add testing2
Traceback (most recent call last):
  File "/home/pulmo/calendar-cli/calendar-cli.py", line 22, in <module>
    import pytz
ImportError: No module named 'pytz'

But that's not important now, I would be happy if it would work at all again somehow - even without Umlaut...

**Comment by tobixen** [comment]
sorry for the slow response on this, probably it's all too late, but ...

authorization error most likely means there was some problems with password or username.

pytz is one of the required python libraries, it has to be installed separately on python3.

problems with umlauts seems to be in the vobject library, perhaps the wrong version has been used.

Closing this issue.
