### ISSUE TITLE
Ugly AssertationError without config

### ISSUE THREAD

**Issue by ketograph** [tobixen/calendar-cli#56]
When installing and just calling `calendar-cli` without any configuration added, an AssertationError is thrown. 
For a better user experience, display a warning about the missing configuration.

```
Traceback (most recent call last):
  File "/usr/bin/calendar-cli", line 4, in <module>
    __import__('pkg_resources').run_script('calendar-cli==0.0.0', 'calendar-cli')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.7/site-packages/calendar_cli-0.0.0-py3.7.egg/EGG-INFO/scripts/calendar-cli", line 911, in <module>
  File "/usr/lib/python3.7/site-packages/calendar_cli-0.0.0-py3.7.egg/EGG-INFO/scripts/calendar-cli", line 901, in main
  File "/usr/lib/python3.7/site-packages/calendar_cli-0.0.0-py3.7.egg/EGG-INFO/scripts/calendar-cli", line 118, in caldav_connect
  File "/usr/lib/python3.7/site-packages/caldav-0.6.1-py3.7.egg/caldav/davclient.py", line 96, in __init__
    if self.url.username is not None:
AttributeError: 'NoneType' object has no attribute 'username'
```

**Comment by tobixen** [comment]
That's rather ugly.  I guess I never attempted using it myself without a valid config file :-)
