### ISSUE TITLE
date_search() got an unexpected keyword argument 'expand'

### ISSUE THREAD

**Issue by DigiAngel** [tobixen/calendar-cli#58]
Topic:
~~~
Traceback (most recent call last):
  File "calendar-cli.py", line 937, in <module>
    main()
  File "calendar-cli.py", line 934, in main
    ret = args.func(caldav_conn, args)
  File "calendar-cli.py", line 480, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend, expand=True)
TypeError: date_search() got an unexpected keyword argument 'expand'
~~~

anything else I can provide?  Python 2.7.17.

**Comment by tobixen** [comment]
Probably the python caldav library needs to be upgraded to a newer version

**Comment by DigiAngel** [comment]
That's unfortunate as I just installed via apt today:
~~~
ii  python-caldav                          0.4.0-1 
~~~
am I out of luck?

**Comment by DigiAngel** [comment]
Yea...I see it in the setup.py 0.5.0 or greater...thank you.
